[access-15] Change landing page to dashboard
dev-tea-party/dev-access pull request #23
Opened 2017-03-07 17:52 UTC by litocabornay

These changes able to change landing page to dashboard. Please see sub tasks.

2017-03-08 01:22 UTC, cjestal commented
lits, pakitanggal sa mga commented codes ug white lines

2017-03-08 23:46 UTC, litocabornay commented
removing commented codes and white lines.

2017-03-10 14:31 UTC, rosoarv requested changes

2017-03-10 14:31 UTC, rosoarv commented on resources/views/home.blade.php
> +        </div> -->
@litocabornay please remove commented code. thanks!

2017-03-12 12:20 UTC, rosoarv approved these changes

2017-03-12 12:20 UTC, rosoarv commented
@litocabornay nice. please merge to master. thanks!

2017-03-12 12:22 UTC, merged