[Access-28] Modify Routes and Display Materials based on Job order.
dev-tea-party/dev-access pull request #45
Opened 2017-03-12 17:17 UTC by jandyl-casas

Please review.

2017-03-13 12:50 UTC, rosoarv requested changes
@jandyl-casas use the MaterialsController since it already has the CRUD operations for the materials

2017-03-13 12:50 UTC, rosoarv commented on app/Http/Controllers/Projects/JobOrderController.php
> +    public function materials($id)
@jandyl-casas no need to create new method for the materials, use the MaterialsController

2017-03-13 12:50 UTC, rosoarv commented on routes/web.php
> +Route::get('/projects/job-order/{id}/materials', 'Projects\\JobOrderController@materials');
use the MaterialsController

2017-03-15 14:41 UTC, rosoarv requested changes

2017-03-15 14:41 UTC, rosoarv commented on app/Http/Controllers/Projects/MaterialsController.php
> +    public function index($id)
please use `$job_id` since it's under MaterialsController

2017-03-15 14:41 UTC, rosoarv commented on app/Http/Controllers/Projects/MaterialsController.php
> +    public function show($id, $matid)
please change to `show($job_id, $mat_id)`

2017-03-15 14:41 UTC, rosoarv commented on app/Http/Controllers/Projects/MaterialsController.php
> +        $material = Material::findOrFail($matid);
use `$mat_id`

2017-03-15 14:41 UTC, rosoarv commented on routes/web.php
> +Route::get('projects/job-order/{id}/materials/{matid}/edit', 'Projects\\MaterialsController@edit');
isn't it redundant since there's already a resource route `Route::resource('projects/job-order/{id}/materials', 'Projects\\MaterialsController');`?

2017-03-15 16:46 UTC, jandyl-casas commented on routes/web.php
> +Route::get('projects/job-order/{id}/materials/{matid}/edit', 'Projects\\MaterialsController@edit');
This is needed in order to get both the job_id and mat_id which is used on each respective functions.

2017-03-15 16:54 UTC, rosoarv commented on routes/web.php
> +Route::get('projects/job-order/{id}/materials/{matid}/edit', 'Projects\\MaterialsController@edit');
try changing `$id` to `$job_id` and retain `$id` as default argument to the MaterialsController methods. And add `$job_id` as another argument.

2017-03-15 18:10 UTC, rosoarv requested changes

2017-03-15 18:10 UTC, rosoarv commented on app/Http/Controllers/Projects/MaterialsController.php
> -
why not just add the where clause to retain the search functionality

2017-03-16 01:43 UTC, rosoarv commented on app/Http/Controllers/Projects/MaterialsController.php
> +                ->paginate($perPage);
:+1:

2017-03-16 01:44 UTC, rosoarv approved these changes

2017-03-16 01:44 UTC, rosoarv commented on app/Http/Controllers/Projects/MaterialsController.php
> +                })->where(function ($query) use ($job_id) {
:+1:

2017-03-16 16:06 UTC, rosoarv commented
@jandyl-casas please merge to master. thanks!

2017-03-17 14:23 UTC, merged