[access-43] Validation: Job Order Module
dev-tea-party/dev-access pull request #46
Opened 2017-03-14 11:13 UTC by shernaleeuy

Done adding validation rules for Job Order Module forms [access-43][https://github.com/dev-tea-party/dev-access/compare/access-43?expand=1]

2017-03-14 13:25 UTC, rosoarv requested changes
only change the codes necessary to the issue

2017-03-14 13:25 UTC, rosoarv commented on app/Http/Controllers/Projects/JobOrderController.php
> +    return view('job-order.create',compact('projectcodes'));
don't remove indent

2017-03-14 13:25 UTC, rosoarv commented on app/Http/Controllers/Projects/JobOrderController.php
> +        */
what is this comment for?

2017-03-14 13:25 UTC, rosoarv commented on app/Http/Controllers/Projects/JobOrderController.php
> -        JobOrder::create($requestData);
don't remove the space

2017-03-14 13:25 UTC, rosoarv commented on resources/views/job-order/create.blade.php
> +
refrain from changing the spaces

2017-03-14 13:52 UTC, shernaleeuy commented
ok sir noted!

2017-03-15 16:59 UTC, micosolon commented
cannot make create job order without project code. i cannot proceed

2017-03-15 17:26 UTC, jandyl-casas commented
add new project through:
'http://127.0.0.1:8000/projects/project-manage'

2017-03-15 17:57 UTC, rosoarv requested changes

2017-03-15 17:57 UTC, rosoarv commented on app/Http/Controllers/Projects/JobOrderController.php
> +            'prj_id' => 'required|unique:id|numeric'
does prj_id really have to be unique?

2017-03-15 17:58 UTC, rosoarv commented on app/Http/Controllers/Projects/JobOrderController.php
> +            'prj_id' => 'required|unique:id|numeric'
and also, it'll cause an error after creating a job-order with project id

2017-03-18 09:44 UTC, micosolon approved these changes

2017-03-18 15:34 UTC, shernaleeuy commented
Kindly check the updated code for Job Order Controller.  Can now create new job order [access-43](https://github.com/dev-tea-party/dev-access/pull/46
)

2017-03-19 02:56 UTC, rosoarv approved these changes

2017-03-19 02:56 UTC, rosoarv commented
@shernaleeuy please merge to master. thanks!

2017-03-22 01:46 UTC, merged